var config = [

/****************************************** 		level 1 ----------- animals 		******************************************/
{level:"1", theme: "animals", question: "When and which committee suggested the justiciable and non justiciable types of Rights?", answers: ["Sapru Committee", "Balwant Rai Mehta Committee", "Bhurelal committee", "None of the above"], correct: 1},
{level:"1", theme: "animals", question: "What are the ideals that a state must keep in mind while framing policies called?", answers: ["Fundamental Rights ", "Directive Principles of State Policy", "Gandhian Principles", "Socialism"], correct: 2},
{level:"1", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "animals", question: "Which of the following statements is true regarding DPSP?    i) The concept was mentioned in Government of India Act 1935   ii) DPSP are not legally enforceable", answers: ["Only i", "Only ii", "Both i and ii", "None of the above "], correct: 3},
{level:"1", theme: "animals", question: "Which of the following articles consists of equal pay for equal work for men and women?", answers: ["Article 31", "Article 39A", "Article 41", "Article 39"], correct: 3},
{level:"1", theme: "animals", question: "Which article states about Uniform Civil Code throughout the country?", answers: ["Article 48", "Article 44", "Article 42", "Article 49"], correct: 1},
{level:"1", theme: "animals", question: "Which of the new DPSP was added to the Constitution through the 42nd amendment?", answers: ["To promote equal justice and to provide free legal aid to the poor", "Promote international peace and security between nations", "State need to minimise inequalities in income, status, facilities and opportunities", "Prohibit the consumption of intoxicating drinks and drugs "], correct: 1},
/****************************************** 		level 2 ----------- animals 		******************************************/
{level:"2", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- animals 		******************************************/
{level:"3", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- animals 		******************************************/
{level:"4", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- animals 		******************************************/
{level:"5", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},

/****************************************** 		level 1 ----------- plants 		******************************************/
{level:"1", theme: "plants", question: "When and which committee suggested the justiciable and non justiciable types of Rights?", answers: ["Sapru Committee", "Balwant Rai Mehta Committee", "Bhurelal committee", "None of the above"], correct: 1},
{level:"1", theme: "plants", question: "What are the ideals that a state must keep in mind while framing policies called?", answers: ["Fundamental Rights ", "Directive Principles of State Policy", "Gandhian Principles", "Socialism"], correct: 2},
{level:"1", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "plants", question: "Which of the following statements is true regarding DPSP?    i) The concept was mentioned in Government of India Act 1935   ii) DPSP are not legally enforceable", answers: ["Only i", "Only ii", "Both i and ii", "None of the above "], correct: 3},
{level:"1", theme: "plants", question: "Which of the following articles consists of equal pay for equal work for men and women?", answers: ["Article 31", "Article 39A", "Article 41", "Article 39"], correct: 3},
{level:"1", theme: "plants", question: "Which article states about Uniform Civil Code throughout the country?", answers: ["Article 48", "Article 44", "Article 42", "Article 49"], correct: 1},
{level:"1", theme: "plants", question: "Which of the new DPSP was added to the Constitution through the 42nd amendment?", answers: ["To promote equal justice and to provide free legal aid to the poor", "Promote international peace and security between nations", "State need to minimise inequalities in income, status, facilities and opportunities", "Prohibit the consumption of intoxicating drinks and drugs "], correct: 1},
/****************************************** 		level 2 ----------- plants 		******************************************/
{level:"2", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- plants 		******************************************/
{level:"3", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- plants 		******************************************/
{level:"4", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- plants 		******************************************/
{level:"5", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},


/****************************************** 		level 1 ----------- water 		******************************************/
{level:"1", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- water 		******************************************/
{level:"2", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- water 		******************************************/
{level:"3", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- water 		******************************************/
{level:"4", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- water 		******************************************/
{level:"5", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},


/****************************************** 		level 1 ----------- safety 		******************************************/
{level:"1", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- safety 		******************************************/
{level:"2", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- safety 		******************************************/
{level:"3", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- safety 		******************************************/
{level:"4", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- safety 		******************************************/
{level:"5", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},



/****************************************** 		level 1 ----------- food 		******************************************/
{level:"1", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- food 		******************************************/
{level:"2", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- food 		******************************************/
{level:"3", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- food 		******************************************/
{level:"4", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- food 		******************************************/
{level:"5", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},

];